// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: proto/currency-converter.proto

package currency_converter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConverterServiceClient is the client API for ConverterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConverterServiceClient interface {
	ConvertMoney(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
}

type converterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConverterServiceClient(cc grpc.ClientConnInterface) ConverterServiceClient {
	return &converterServiceClient{cc}
}

func (c *converterServiceClient) ConvertMoney(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, "/proto.ConverterService/ConvertMoney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConverterServiceServer is the server API for ConverterService service.
// All implementations must embed UnimplementedConverterServiceServer
// for forward compatibility
type ConverterServiceServer interface {
	ConvertMoney(context.Context, *ConvertRequest) (*ConvertResponse, error)
	mustEmbedUnimplementedConverterServiceServer()
}

// UnimplementedConverterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConverterServiceServer struct {
}

func (UnimplementedConverterServiceServer) ConvertMoney(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertMoney not implemented")
}
func (UnimplementedConverterServiceServer) mustEmbedUnimplementedConverterServiceServer() {}

// UnsafeConverterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConverterServiceServer will
// result in compilation errors.
type UnsafeConverterServiceServer interface {
	mustEmbedUnimplementedConverterServiceServer()
}

func RegisterConverterServiceServer(s grpc.ServiceRegistrar, srv ConverterServiceServer) {
	s.RegisterService(&ConverterService_ServiceDesc, srv)
}

func _ConverterService_ConvertMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConverterServiceServer).ConvertMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ConverterService/ConvertMoney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConverterServiceServer).ConvertMoney(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConverterService_ServiceDesc is the grpc.ServiceDesc for ConverterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConverterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ConverterService",
	HandlerType: (*ConverterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertMoney",
			Handler:    _ConverterService_ConvertMoney_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/currency-converter.proto",
}
